### ISSUE TITLE
passwords greater than 32 characters prompt a "username too long" error

### ISSUE THREAD

**Issue by ldpr** [torrust/torrust-index-gui#613] opened 2024-09-06 11:55 UTC
![aaaaaaaaaaaa](https://github.com/user-attachments/assets/41875528-1c2b-4c97-bfe6-02a16d0c4073)

Tested against the newest alpha running on the demo site.

**Comment by josecelano** [comment] 2024-09-06 12:04
Hi @ldpr, Thank you for reporting. I'm checking it, but I think the problem is not the password. The error message must be wrong.

I've tried with these values and works:

- username: `user123456789`
- email: `user123456789@gmail.com`
- pwd: `123456789123456789123456789123456789`

![image](https://github.com/user-attachments/assets/7a9506a3-f48a-4697-8775-1f1d9fc1f985)

**Comment by josecelano** [comment] 2024-09-06 12:13
@ldpr can you share the password you tried?

I can't reproduce it on the demo site:

![image](https://github.com/user-attachments/assets/d6a918a5-81d2-49c1-b6fd-59f43bb3986b)

**Comment by josecelano** [comment] 2024-09-06 12:20
@ldpr I was able to reproduce it. The limit is 63 chars, not 32. I don't know why 😮

**Comment by josecelano** [comment] 2024-09-06 12:26
The limit is set in the configuration, it's the default value. I didn't remember that even if I  was the one who did configuration overhaul 🫨.

```toml
[auth.password_constraints]
max_password_length = 64
min_password_length = 6
```

The message is a copy/paste typo. I'm fixing it:

```rust
    #[display(fmt = "Password too short")]
    PasswordTooShort,
    #[display(fmt = "Password too long")]  // <- This was wrong
    PasswordTooLong,
    #[display(fmt = "Passwords don't match")]
    PasswordsDontMatch,
```

**Comment by josecelano** [comment] 2024-09-06 12:33
Fixing error message on https://github.com/torrust/torrust-index/pull/725 ...

**Comment by josecelano** [comment] 2024-09-06 12:51
I have also realized min (6) and max (64) values are not valid. I'm also changing that. So passwords with 6 or 64 chars will also be allowed.

**Comment by josecelano** [comment] 2024-09-06 16:25
Fixed via https://github.com/torrust/torrust-index/issues/724

![image](https://github.com/user-attachments/assets/0dda4119-e256-4ec0-aee8-e4c88c3525eb)

**Closed as completed by josecelano** 2024-09-06 16:25 UTC
Labels: Bug
